# Generated by Django 3.1.2 on 2022-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220617_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tamanio', models.IntegerField(choices=[[0, 'Pequeño'], [1, 'Mediano'], [2, 'Grande']])),
                ('edad', models.IntegerField()),
                ('sexo', models.IntegerField(choices=[[0, 'Macho'], [1, 'Hembra']])),
                ('microchip', models.CharField(max_length=50)),
                ('vacunado', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='adopciones')),
            ],
        ),
    ]
