# Generated by Django 3.1.2 on 2022-06-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adopcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_adopcion', models.IntegerField(choices=[[0, 'Adoptar'], [1, 'Apadrinar']])),
                ('mensaje', models.TextField()),
                ('suscripcion', models.BooleanField()),
            ],
        ),
    ]
