# Generated by Django 3.1.2 on 2022-06-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220627_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto1',
            name='avisos',
        ),
    ]
