# Generated by Django 3.1.2 on 2022-07-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_suscripcion_fecha_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='id_usuario',
        ),
    ]
